apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: apicontagem 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apicontagem 
    spec:
      containers:
        - name: apicontagem 
          image: groffeazuredevops.azurecr.io/apicontagem
          ports:
          - containerPort: 80